name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: main
    paths:
      - "docs/nodes/**"
      - "examples/**"
      - "src/**"
      - "ui/**"
      - "test/**"
      - ".npmignore"
      - "package*.json"

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: npm install
        run: npm ci
      - name: npm lint
        run: npm run lint
      - name: npm test
        run: npm test
        env:
          CI: true

  release-please:
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          bump-minor-pre-major: true
