name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "examples/**"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # For last-updated time

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: npm
      - run: npm ci
      - run: npm run docs:build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/.vuepress/dist
          force_orphan: true
